name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Stop the existing Application (if running)
        run: pkill -f "node ." || true

      - name: Run Deploy Commands
        run: node ./deployCommands.js

      - name: Restart Main App
        run: nohup node . &

      - name: Wait for the Application to finish
        run: sleep 10
